name: 'datadog-metrics-reporter'
description: 'Report CI metrics to datadog'
author: 'Drew Wyatt <drew.j.wyatt@gmail.com>'
inputs:
  datadog-api-key:
    required: true
    description: 'not an app key'
  github-token:
    required: true
    description: 'probably secrets.GITHUB_TOKEN'
runs:
  using: 'node12'
  main: 'dist/index.js'
