name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    required: true
    description: 'probably {{secrets.GITHUB_TOKEN}}'
runs:
  using: 'node12'
  main: 'dist/index.js'
