name: 'CI'
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn build
      - run: yarn package
      - name: 'Fail if there is a dirty working copy (i.e. we forgot to check in artifacts)'
        run: git diff --exit-code
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn lint
      - run: yarn format
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: yarn
      - run: yarn test
  e2e:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          datadog-api-key: ${{secrets.DATADOG_API_KEY}}
