name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          yarn
      - run: |
          yarn all

  check_for_artifacts:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - run: |
          git diff --exit-code

  test:
    runs-on: ubuntu-latest
    needs: [build]
    if: always()
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          datadog-api-key: ${{secrets.DATADOG_API_KEY}}
